### ISSUE TITLE
Bug: github action "Release" docker container workflows are broken

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/docs#374]
### Describe the bug

Looks like the Docker container builds on the release actions are broken:

https://github.com/open-sauced/docs/actions/runs/10456277985/job/28953223937

Running docker builds locally yields the same "broken link" results:

```
docker build .
```

```
#0 16.51 [ERROR] Error: Unable to build website for locale en.
#0 16.51     at tryToBuildLocale (/app/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
#0 16.51     at async /app/node_modules/@docusaurus/core/lib/commands/build.js:65:9
#0 16.51     at async mapAsyncSequential (/app/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
#0 16.51     at async Command.build (/app/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
#0 16.51   [cause]: Error: Docusaurus found broken links!
#0 16.51
#0 16.51   Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
#0 16.51   Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
#0 16.51
#0 16.51   It looks like some of the broken links we found appear in many pages of your site.
#0 16.51   Maybe those broken links appear on all pages through your site layout?
#0 16.51   We recommend that you check your theme configuration for such links (particularly, theme navbar and footer).
#0 16.51   Frequent broken links are linking to:
#0 16.51   - /community-resources/
#0 16.51
#0 16.51   Exhaustive list of all broken links found:
```

### Steps to reproduce

1. Checkout repo locally
2. Run docker build via `docker build .`

**Comment by jpmcb** [comment]
Looks like maybe this release action isn't really needed anymore? This workflow hasn't completed successfully in a few months now.

**Comment by BekahHW** [comment]
@jpmcb this has been on my radar. I'm trying to hunt down the broken links. When we redirected docs as a subdirectory, it caused some issues.

**Comment by rajanarahul93** [comment]
@BekahHW I’m picking this up and will open a PR shortly.
